/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SonarTesting;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    /*@Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertEquals(15,classUnderTest);*/
    }

